name: deploy-api
on:
  push:
      branches:
        - 'master'
      paths: 
        - 'packages/api/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn --frozen-lockfile
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ARN }}
          role-session-name: ${{ vars.AWS_ROLE_SESSION_NAME }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: yarn prisma generate
        working-directory: ./packages/api 
      - run: yarn build
        working-directory: ./packages/api 
      - run: yarn serverless deploy
        working-directory: ./packages/api 
        env:
          SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID}} 
          PRIVATE_SUBNET_1_ID: ${{ secrets.PRIVATE_SUBNET_1_ID}} 
          PRIVATE_SUBNET_2_ID: ${{ secrets.PRIVATE_SUBNET_2_ID}} 
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN}} 
          DATABASE_URL: ${{ secrets.DATABASE_URL}}
