name: deploy-api
on:
  push:
      branches:
        - 'master'
      paths: 
        - 'packages/api/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: yarn --frozen-lockfile
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: cd packages/api
      - run: yarn prisma generate
      - run: pwd
      - run: yarn build
      - run: yarn serverless deploy
